version: "3.9"

services:
  frontend:
    build: ./frontend # Path to your Next.js Dockerfile
    ports:
      - "3000:3000" # Expose frontend to outside
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    build: ./backend # Path to your Spring Boot Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
      - SERVER_PORT=8080
    expose:
      - "8080" # Only accessible to other containers
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432" # Accessible only inside Docker network

volumes:
  db_data:
